import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TODO from '../components/TODO/todo'
import EXAMPLE from '../components/EXAMPLE/example'
import FOOTER from '../components/FOOTER/footer'


export default function Home() {
  return (
    <body className={styles.container}>
    <div >
      <Head>
        <title>TODO-list </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.main}>TODO LIST</h1>
      <TODO/>
     <FOOTER/>
    </div>
    </body>
  )
}
